//
// Created by CONG YU on 2019/10/1.
//

#ifndef LINKER_EXCEPTION_H
#define LINKER_EXCEPTION_H

enum SYNTAX_ERROR {
    NUMBER_EXPECTED,
    SYMBOL_EXPECTED,
    ADDR_EXPECTED,
    SYM_TOO_LONG,
    TOO_MANY_DEF_IN_MODULE,
    TOO_MANY_USE_IN_MODULE,
    TOO_MANY_INSTR
};



#endif //LINKER_EXCEPTION_H
